### ISSUE TITLE
No connection to the arm at all

### ISSUE THREAD

**Issue by FineApple-de** [dorna-robotics/dorna#25]
After a few days of fail and error to connect the arm with my desktop, I hope you can help. 

I used the arm before and everything works out fine, he did what he should do but now, I don´t even get a connection to the arm. 
Maybe I should mention, that I don´t really have a plan of programming, I know some basics and how to use and interact with software.
![image](https://user-images.githubusercontent.com/59649440/71975952-795c1000-3215-11ea-9a8d-fada2c77c419.png)

Following a list of what i´ve done and which response I get from the software. 
1.	

- a.	Connecting the USB to the desktop 

- b.	Starting the software

- c.	“refresh the USB port” and trying to connect 

- d.	Response from the software:

i.	Desktop\Dorna.2.2 Windows-64\dorna\api.py:2366: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
ii.	Progressing...
iii.	('send: ', '{line:n}')
iv.	('sleep: :', 0.04999999999999993)
v.	('send: ', ' n 2')
vi.	('sleep: :', 0.04999999999999993)
vii.	('send: ', '{id: n, fv:n}')
viii.	('sleep: :', 0.04999999999999993)
ix.	('send: ', ' n 4')
x.	('sleep: :', 0.04999999999999993)

- e.	“reset device”

- f.	Response from the software

i.	Progressing...
ii.	Exception in thread Thread-30:
iii.	Traceback (most recent call last):
iv.	  File "threading.py", line 917, in _bootstrap_inner
v.	  File "threading.py", line 865, in run
vi.	  File "subprocess.py", line 1238, in _readerthread
vii.	  File "c:\users\hossein\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
viii.	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>
ix.	
x.	(IndexError('list index out of range'),)
xi.	Exception in thread Thread-32:
xii.	Traceback (most recent call last):
xiii.	  File "threading.py", line 917, in _bootstrap_inner
xiv.	  File "threading.py", line 865, in run
xv.	  File "subprocess.py", line 1238, in _readerthread
xvi.	  File "c:\users\hossein\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
xvii.	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>
xviii.	
xix.	(IndexError('list index out of range'),)
xx.	Exception in thread Thread-34:
xxi.	Traceback (most recent call last):
xxii.	  File "threading.py", line 917, in _bootstrap_inner
xxiii.	  File "threading.py", line 865, in run
xxiv.	  File "subprocess.py", line 1238, in _readerthread
xxv.	  File "c:\users\hossein\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
xxvi.	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>
xxvii.	
xxviii.	(IndexError('list index out of range'),)
xxix.	Exception in thread Thread-36:
xxx.	Traceback (most recent call last):
xxxi.	  File "threading.py", line 917, in _bootstrap_inner
xxxii.	  File "threading.py", line 865, in run
xxxiii.	  File "subprocess.py", line 1238, in _readerthread
xxxiv.	  File "c:\users\hossein\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
xxxv.	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>
xxxvi.	
xxxvii.	(IndexError('list index out of range'),)
xxxviii.	Exception in thread Thread-38:
xxxix.	Traceback (most recent call last):
xl.	  File "threading.py", line 917, in _bootstrap_inner
xli.	  File "threading.py", line 865, in run
xlii.	  File "subprocess.py", line 1238, in _readerthread
xliii.	  File "c:\users\hossein\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
xliv.	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>
xlv.	
xlvi.	(IndexError('list index out of range'),)
xlvii.	Exception in thread Thread-40:
xlviii.	Traceback (most recent call last):
xlix.	  File "threading.py", line 917, in _bootstrap_inner
l.	  File "threading.py", line 865, in run
li.	  File "subprocess.py", line 1238, in _readerthread
lii.	  File "c:\users\hossein\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
liii.	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>
liv.	
lv.	(IndexError('list index out of range'),)
lvi.	Exception in thread Thread-42:
lvii.	Traceback (most recent call last):
lviii.	  File "threading.py", line 917, in _bootstrap_inner
lix.	  File "threading.py", line 865, in run
lx.	  File "subprocess.py", line 1238, in _readerthread
lxi.	  File "c:\users\hossein\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
lxii.	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>
lxiii.	
lxiv.	(IndexError('list index out of range'),)
lxv.	Exception in thread Thread-44:
lxvi.	Traceback (most recent call last):
lxvii.	  File "threading.py", line 917, in _bootstrap_inner
lxviii.	  File "threading.py", line 865, in run
lxix.	  File "subprocess.py", line 1238, in _readerthread
lxx.	  File "c:\users\hossein\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
lxxi.	UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20: character maps to <undefined>
lxxii.	
lxxiii.	(IndexError('list index out of range'),)

That´s it.  I don´t know if the lines help, but maybe they´ll do. 

All the best and thanks for helping me.

FineApple-de

**Comment by sudosurf** [comment]
I also have major issues with connecting over USB. Some days I can connect quickly, other days I don't get a connection all day. I've tried different computers, python command line, python program, included GUI. They all have this issue. Could this be an issue with the g2core firmware?

**Comment by virtualmagician** [comment]
same issue for me. 
connection to arm worked only once in 100+ connection attempts.

**Comment by FullMetalRico** [comment]
So, is there any solution to this ? I am facing the exact same problem and i would like to flash a fresh g2core but as far as i understand the arm will not work then because of the different pinout. Is is possible to get the original .bin or the pinout?

**Comment by mechaphone** [comment]
I had the same issue for a long time and found the solution that seems to work.
Apperantly you have to reset the Arduino Due. The problem is that it is hidden on the floor of the controller box.
If you drill a small hole you can dip the reset button wit a wooden(!!!) stick. After you reset the Arduino Due the software will connect and you are good to go!

The opening needs to be right here and the sick goes about 2 to 3 cm in. Then just tilt it and you'll hear the click.
Watch the terminal and see the magic happen ;)
 
![IMG20210525120047](https://user-images.githubusercontent.com/48671001/119480654-2e7f6180-bd52-11eb-9b12-8a72792c603c.jpg)

https://user-images.githubusercontent.com/48671001/119480634-29221700-bd52-11eb-9040-70443ce405cf.mp4
