### ISSUE TITLE
_xyz_to_joint error

### ISSUE THREAD

**Issue by mfogelson** [dorna-robotics/dorna#4]
Two things
1) I believe this function should not but "private" since it is super helpful for users so consider renaming it

2) when I run this function I get a type error "bool" is not iterable
Solution: 
Comment out the initial check,
if any(xyz == None):

**Comment by smhty** [comment]
@mfogelson 
1. Good point, I will mention this function in the Wiki page, as a helper method.
2. How do you call this function, because the line yo commented is checking if the input (input position in the Cartesian space) is valid or not. Can you explain it more so we can fix it :)

**Comment by mfogelson** [comment]
Hey so I would probably put it as a try and except condition statement shown below.  I would also add some sort of print or log of the exception encountered like print("[Error]: Dorna_Api: _xyz_to_joint method: xyz not of proper type needs to be list of length 5 or 6" :
```
try:
			if type(xyz) == list and (len(xyz) == 5 or len(xyz) == 6) and None not in xyz:
				x = xyz[0]
				y = xyz[1]
				z = xyz[2]
				alpha = xyz[3]
				beta = xyz[4]

				alpha = math.radians(alpha)
				beta = math.radians(beta)

				# first we find the base rotation
				teta_0 = math.atan2(y, x)

				# next we assume base is not rotated and everything lives in x-z plane
				x = math.sqrt(x ** 2 + y ** 2)

				# next we update x and z based on base dimensions and hand orientation
				x -= (self._bx + self._config["toolhead"]["x"] * math.cos(alpha))
				z -= (self._bz + self._config["toolhead"]["x"] * math.sin(alpha))

				# at this point x and z are the summation of two vectors one from lower arm and one from upper arm of lengths l1 and l2
				# let L be the length of the overall vector
				# we can calculate the angle between l1 , l2 and L
				L = math.sqrt(x ** 2 + z ** 2)
				L = np.round(L,13) # ???
				# not valid
				if L > (self._l1 + self._l2) or self._l1 > (self._l2 + L) or self._l2 > (self._l1 + L):  # in this case there is no solution
					return {"joint": np.array([None for i in range(len(xyz))]), "status": 2}
				
				# init status
				status = 0
				if L > (self._l1 + self._l2) - self._delta_e or self._l1 > (self._l2 + L) - self._delta_e: # in this case there is no solution
					status = 1 

				teta_l1_L = math.acos((self._l1 ** 2 + L ** 2 - self._l2 ** 2) / (2 * self._l1 * L))  # l1 angle to L
				teta_L_x = math.atan2(z, x)  # L angle to x axis
				teta_1 = teta_l1_L + teta_L_x
				# note that the other solution would be to set teta_1 = teta_L_x - teta_l1_L. But for the dynamics of the robot the first solution works better.
				teta_l1_l2 = math.acos((self._l1 ** 2 + self._l2 ** 2 - L ** 2) / (2 * self._l1 * self._l2))  # l1 angle to l2
				teta_2 = teta_l1_l2 - math.pi
				teta_3 = alpha - teta_1 - teta_2
				teta_4 = beta
				teta_0 = math.degrees(teta_0)
				teta_1 = math.degrees(teta_1)
				teta_2 = math.degrees(teta_2)
				teta_3 = math.degrees(teta_3)
				teta_4 = math.degrees(teta_4)
				if len(xyz) == 6:
					joint = np.array([teta_0, teta_1, teta_2, teta_3, teta_4, xyz[5]])
				else:
					joint = np.array([teta_0, teta_1, teta_2, teta_3, teta_4])

				return {"joint": joint, "status": status}
			else:
				raise TypeError
		except:
			raise
```
Tests:
```
robot._xyz_to_joint([1,2,3,4,None])
```
```
robot._xyz_to_joint([1,2,3,4,None, 6])
```
```
robot._xyz_to_joint({1})
```
Response:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rit/.local/lib/python3.6/site-packages/dorna/dorna/api.py", line 2164, in _xyz_to_joint
    raise TypeError
TypeError

**Comment by smhty** [comment]
@mfogelson 
The reason you get this error is that the input for both "_xyz_to_joint" and "_joint_to_xyz" is a numpy array (not list).
Try to convert your list to numpy array using the numpy.array method. 
For example:
```python
import numpy as np
from dorna import Dorna

# Dorna instance
robot = Dorna()

# sample list of size 5
sample_list = [0, 0, 0, 0, 0]
sample_array = np.array(sample_list)

# joint to xyz
sample_xyz = robot._xyz_to_joint(sample_array)
#{'joint': array([   0.        , -86.41909076, -92.37169477, 178.79078553, 0.        ]), 'status': 0}
```
